workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - libc++-8-dev
  - libc++abi-8-dev
  - python3.8-dev
  - python3.8-venv
  - llvm-8
  - clang-8
  - clang-format-8
  - clang-tools-8
  - build-essential
  - expect
  - git
  - ccache
  - kmod # modinfo for sgxinfo.sh
  - cmake
  - libssl-dev
  - jq # operation scripts
  - sudo
  - curl # client test infra
  - shellcheck # bash lint
  - iptables # partition test infra
  - flex # required to build doxygen
  - bison # required to build doxygen

mbedtls_ver: "2.16.10"
mbedtls_dir: "mbedtls-{{ mbedtls_ver }}"
mbedtls_src: "{{ mbedtls_dir }}.tar.gz"

doxygen_ver: "1_9_1"
doxygen_dir: "Release_{{ doxygen_ver }}"
doxygen_src: "{{ doxygen_ver }}.tar.gz"
