parameters:
  suite_name_suffix: ""

steps:
  # Whether tests pass or fail, print out a per-logfile, and total number of I/O operations that
  # exceeded our opinion of "too long". Also keep track of the total number per job in cimetrics
  # in case any trends emerge.
  - script: |
      sudo apt install ripgrep > /dev/null
      echo "TOOK TOO LONG "
      echo "-------------------------------------"
      rg "Took too long" --count
      echo "-------------------------------------"
      echo "TOOK TOO LONG TOTAL"
      echo "-------------------------------------"
      rg "Took too long" --count | cut -d : -f 2 | awk '{ sum += $1 } END { print sum }'
    workingDirectory: build
    displayName: "Took too long metrics"
    condition: succeededOrFailed()

  - script: |
      if [ -n "$METRICS_MONGO_CONNECTION" ]; then
        ./cimetrics_env.sh
        source env/bin/activate
        rg "Took too long" --count | cut -d : -f 2 | python ../tests/upload_misc.py "took_too_long_count_${{ parameters.suite_name_suffix }}"
      fi
    env:
      METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
    workingDirectory: build
    displayName: "Upload took too long metrics"
    condition: succeededOrFailed()
