parameters:
  target: ""

steps:
  # 119 is GID of special "sgx_prv" group on underlying VM that is
  # required to run SGX on kernel > 5.11
  - ${{ if eq(parameters.target, 'SGX') }}:
      - script: |
          set -ex
          SGX_GROUP_ID=$(grep sgx_prv /tmp/host_group | cut -d ':' -f 3)
          sudo groupadd -g $SGX_GROUP_ID sgx_prv
          sudo usermod -a -G sgx_prv $(whoami)
        displayName: SGX Group
        condition: succeededOrFailed()

      - script: |
          set -ex
          samples/scripts/sgxinfo.sh
          cat /proc/cpuinfo | grep flags | uniq
        displayName: SGX Info
        condition: succeededOrFailed()

  - ${{ if ne(parameters.target, 'SGX') }}:
      - script: |
          set -ex
          samples/scripts/snpinfo.sh
        displayName: SEV-SNP Info
        condition: succeededOrFailed()
