jobs:
  - job: GitHubRelease
    displayName: "GitHub Release"
    dependsOn: ${{ parameters.depends_on }}

    ${{ insert }}: ${{ parameters.env }}

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          patterns: "**"
          path: $(Build.ArtifactStagingDirectory)

      - script: |
          set -ex
          python3.8 ./scripts/extract-release-notes.py --target-git-version --append-mcr-images | tee $(Build.BinariesDirectory)/rel-notes.md
        displayName: Extract release notes

      - script: |
          set -ex
          cd $(Build.ArtifactStagingDirectory)
          rename.ul + _ *+*.deb || true
          ls $(Build.ArtifactStagingDirectory)
        displayName: Remove characters that break GitHubRelease

      - task: EsrpCodeSigning@4
        inputs:
          ConnectedServiceName: 'ESRP Code Signing 2023'
          FolderPath: '$(Build.ArtifactStagingDirectory)'
          Pattern: '*.deb'
          signConfigType: 'inlineSignParams'
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'
          PendingAnalysisWaitTimeoutMinutes: '5'

      - task: GitHubRelease@0
        inputs:
          gitHubConnection: ccf_release
          repositoryName: "$(Build.Repository.Name)"
          action: "create"
          target: "$(Build.SourceVersion)"
          tagSource: "auto"
          assets: $(Build.ArtifactStagingDirectory)/**/*
          assetUploadMode: "delete"
          isDraft: true
          isPreRelease: true
          releaseNotesSource: "file"
          releaseNotesFile: $(Build.BinariesDirectory)/rel-notes.md
          addChangeLog: false
        displayName: "GitHub Release"
