steps:
  - script: |
      set -ex
      sudo apt update
      sudo apt install -y default-jre parallel
      python3 ./tla/install_deps.py
    displayName: "Install TLA dependencies"

  - script: |
      set -ex
      set -o pipefail
      cd tla/
      parallel 'echo {} && JSON={} ./tlc.sh -dump dot,constrained,colorize,actionlabels {}.dot consensus/Traceccfraft.tla' ::: $(ls ../build/*.ndjson | grep -v _deprecated)
    displayName: "Run trace validation"

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: "Trace Validation Output"
      targetPath: tla
    condition: or(failed(), canceled())
