steps:
  - script: |
      set -ex
      sudo apt update
      sudo apt install -y default-jre parallel
      python3 ./tla/install_deps.py
    displayName: "Install TLA dependencies"

  - script: |
      set -ex
      cd tla/
      parallel 'JSON={} ./tlc.sh consensus/Traceccfraft.tla' ::: \
      ../build/replicate_deprecated.ndjson \
      ../build/election_deprecated.ndjson \
      ../build/multi_election_deprecated.ndjson \
      ../build/check_quorum_deprecated.ndjson \
      ../build/reconnect_deprecated.ndjson \
      ../build/reconnect_node_deprecated.ndjson \
      ../build/bad_network_deprecated.ndjson \
      ../build/fancy_election.1_deprecated.ndjson \
      ../build/fancy_election.2_deprecated.ndjson \
      ../build/suffix_collision.1_deprecated.ndjson \
      ../build/suffix_collision.2_deprecated.ndjson \
      ../build/suffix_collision.3_deprecated.ndjson
    displayName: "Run trace validation"
