steps:
  - script: |
      set -ex
      sudo apt update
      sudo apt install -y default-jre
      python3 ./tla/install_deps.py
    displayName: "Install TLA dependencies"

  - script: |
      set -ex
      cd tla/
      JSON=../build/election_while_reconfiguration.ndjson ./tlc.sh Traceccfraft.tla
      echo $?
      echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
      JSON=../build/replicate.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/election.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/multi_election.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/check_quorum.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/reconnect.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/reconnect_node.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/bad_network.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/fancy_election.1.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/fancy_election.2.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/suffix_collision.1.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/suffix_collision.2.ndjson ./tlc.sh Traceccfraft.tla
      JSON=../build/suffix_collision.3.ndjson ./tlc.sh Traceccfraft.tla
    displayName: "Run trace validation"
