name: "Continous Benchmarking"

on:
    push:
      branches: bencher_experiment
  
jobs:
    benchmark_base_branch:
      name: Continuous Benchmarking with Bencher
      runs-on: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub]
      container:
        image: ccfmsrc.azurecr.io/ccf/ci:2024-04-25-virtual-clang15
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - run: |
            git config --global --add safe.directory /__w/CCF/CCF
            mkdir build
            cd build
            cmake -GNinja -DCOMPILE_TARGET=virtual ..
            ninja
            ./tests.sh -VV -R pi_basic_virtual
            ./tests.sh -VV -R historical_query
            ./tests.sh -VV -R commit_latency

        - uses: bencherdev/bencher@main
        - name: Track base branch benchmarks with Bencher
          run: |
            bencher run \
            --project ccf \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch bencher_experiment \
            --testbed gha-virtual-ccf-sub \
            --adapter json \
            --err \
            --file build/bencher.json