name: CI

on:
  push:
    branches:
      - main
      - gha_ci
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build_and_test:
    name: CI
    strategy:
      matrix:
        platform:
          - name: virtual
            image: ghcr.io/microsoft/ccf/ci/default:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub] 
          - name: snp
            image: ghcr.io/microsoft/ccf/ci/default:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub]
          - name: sgx
            image: ghcr.io/microsoft/ccf/ci/sgx:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-sgx-ccf-sub]
    runs-on: ${{ matrix.platform.nodes }}
    container:
      image: ${{ matrix.platform.image }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Build Debug ${{ matrix.platform.name }}"
        run: |
          git config --global --add safe.directory /__w/CCF/CCF
          mkdir build
          cd build
          cmake -GNinja -DCOMPILE_TARGET=${{ matrix.platform.name }} -DCMAKE_BUILD_TYPE=Debug -DLVI_MITIGATIONS=OFF -DVERBOSE_LOGGING=ON ..
          ninja
        shell: bash

      - name: "Test ${{ matrix.platform.name }}"
        run: |
          cd build
          ASAN_SYMBOLIZER=/usr/bin/llvm-symbolizer-15
          export ASAN_SYMBOLIZER_PATH=$(realpath $(ASAN_SYMBOLIZERS))
          ./tests.sh --timeout 240 --output-on-failure -L e2e
        shell: bash
        if: "${{ matrix.platform.name != 'snp' }}" # Needs 1ES Pool support

      - name: "Upload logs for ${{ matrix.platform.name }}"
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.platform.name }}
          path: build/workspace/