name: "Continuous Integration"

on:
  push:
    branches:
      - main
      - gha_ci
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build_and_test:
    name: Continuous Integration
    strategy:
      matrix:
        platform:
          - name: virtual
            image: ghcr.io/microsoft/ccf/ci/default:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub] 
          - name: snp
            image: ghcr.io/microsoft/ccf/ci/default:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub]
          - name: sgx
            image: ghcr.io/microsoft/ccf/ci/default:build-19-06-2024
            nodes: [self-hosted, 1ES.Pool=gha-sgx-ccf-sub]
    runs-on: ${{ matrix.platform.nodes }}
    container:
      image: ${{ matrix.platform.containers }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Build Debug ${{ matrix.platform.name }}"
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCOMPILE_TARGET=${{ matrix.platform.name }} -DCMAKE_BUILD_TYPE=Debug -DLVI_MITIGATIONS=OFF -DVERBOSE_LOGGING=ON ..
          ninja
        shell: bash

      - name: "Test ${{ matrix.platform.name }}"
        run: |
          cd build
          ./tests.sh -VV --timeout 240 --no-compress-output -T Test
        shell: bash
        if: "${{ matrix.platform.name != 'snp' }}" # Can only run when 1ES pools support SNP

      - name: "Test Report ${{ matrix.platform.name }}"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: CTests
          path: build/Testing/*/Test.xml
          reporter: jest-junit