name: "Doc"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build_and_publish_doc:
    name: Build Doc
    runs-on: [self-hosted, 1ES.Pool=gha-virtual-ccf-sub]
    container:
      image: ghcr.io/microsoft/ccf/ci/default:build-26-06-2024
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Documentation
        run: |
          set -x
          python3.8 -m venv env
          source env/bin/activate
          pip install -U pip
          pip install -U -e ./python
          pip install -U -r doc/requirements.txt
          pip install -U -r doc/historical_ccf_requirements.txt
          sphinx-multiversion -D smv_remote_whitelist=origin doc build/html
        shell: bash
