name: "Build and Publish NPM package"

on:
  release:
    types: [published]

env:
  ACR_REGISTRY: ccfmsrc.azurecr.io
  ACR_TOKEN_NAME: app-push-token
  DOCKER_BUILDKIT: 1 # https://docs.docker.com/develop/develop-images/build_enhancements/

jobs:
  build_and_publish:
    name: "Build and publish containers for all platforms"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get release number from git tag (release) or latest (branch)
        run: |
          echo "${GITHUB_REF#refs/tags/ccf-}" >> $GITHUB_OUTPUT
        id: tref

      - name: Fetch NPM Package from release
        run: |
          wget https://github.com/microsoft/CCF/releases/download/ccf-${{steps.tref.outputs.tag}}/microsoft-ccf-app-${{steps.tref.outputs.tag}}.tgz
        


      - name: Publish NPM Package to https://www.npmjs.com/package/@microsoft/ccf-app
        run: |
          set -ex
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish microsoft-ccf-app*.tgz --access public
